import json
from sqlalchemy.orm import Session
from app.models.aircraft import Aircraft
from app.models.weapon import Weapon, WeaponType
from app.models.ship import Ship, ShipType


def seed_hardware(db: Session) -> None:
    """Seed the database with real military hardware data."""

    # ── WEAPONS (must be seeded first, aircraft reference weapon IDs) ──

    weapons = [
        # BVR Air-to-Air Missiles
        {
            "name": "Astra Mk-1",
            "origin": "India",
            "weapon_type": WeaponType.BVR_AAM,
            "weight_kg": 154,
            "max_range_km": 110,
            "no_escape_range_km": 35,
            "min_range_km": 5,
            "speed_mach": 4.0,
            "guidance": "inertial+active_radar",
            "seeker_generation": 3,
            "base_pk": 0.70,
            "warhead_kg": 15,
            "eccm_rating": 65,
            "maneuverability_g": 35,
            "cost_per_unit": 800,
        },
        {
            "name": "Astra Mk-2",
            "origin": "India",
            "weapon_type": WeaponType.BVR_AAM,
            "weight_kg": 160,
            "max_range_km": 160,
            "no_escape_range_km": 60,
            "min_range_km": 5,
            "speed_mach": 4.5,
            "guidance": "inertial+active_radar",
            "seeker_generation": 4,
            "base_pk": 0.75,
            "warhead_kg": 15,
            "eccm_rating": 75,
            "maneuverability_g": 40,
            "cost_per_unit": 1200,
        },
        {
            "name": "AIM-120C AMRAAM",
            "origin": "USA",
            "weapon_type": WeaponType.BVR_AAM,
            "weight_kg": 152,
            "max_range_km": 120,
            "no_escape_range_km": 45,
            "min_range_km": 4,
            "speed_mach": 4.0,
            "guidance": "inertial+active_radar",
            "seeker_generation": 4,
            "base_pk": 0.80,
            "warhead_kg": 18,
            "eccm_rating": 80,
            "maneuverability_g": 40,
            "cost_per_unit": 1100,
        },
        {
            "name": "MICA EM",
            "origin": "France",
            "weapon_type": WeaponType.BVR_AAM,
            "weight_kg": 112,
            "max_range_km": 80,
            "no_escape_range_km": 30,
            "min_range_km": 3,
            "speed_mach": 4.0,
            "guidance": "inertial+active_radar",
            "seeker_generation": 4,
            "base_pk": 0.85,
            "warhead_kg": 12,
            "eccm_rating": 82,
            "maneuverability_g": 50,
            "cost_per_unit": 1000,
        },
        {
            "name": "Meteor",
            "origin": "Europe",
            "weapon_type": WeaponType.BVR_AAM,
            "weight_kg": 190,
            "max_range_km": 200,
            "no_escape_range_km": 80,
            "min_range_km": 5,
            "speed_mach": 4.5,
            "guidance": "inertial+active_radar",
            "seeker_generation": 5,
            "base_pk": 0.90,
            "warhead_kg": 25,
            "eccm_rating": 90,
            "maneuverability_g": 45,
            "cost_per_unit": 2000,
        },
        {
            "name": "R-77",
            "origin": "Russia",
            "weapon_type": WeaponType.BVR_AAM,
            "weight_kg": 175,
            "max_range_km": 110,
            "no_escape_range_km": 40,
            "min_range_km": 5,
            "speed_mach": 4.0,
            "guidance": "inertial+active_radar",
            "seeker_generation": 3,
            "base_pk": 0.70,
            "warhead_kg": 22,
            "eccm_rating": 60,
            "maneuverability_g": 35,
            "cost_per_unit": 700,
        },
        # IR Air-to-Air Missiles (WVR)
        {
            "name": "Python-5",
            "origin": "Israel",
            "weapon_type": WeaponType.IR_AAM,
            "weight_kg": 105,
            "max_range_km": 20,
            "no_escape_range_km": 10,
            "min_range_km": 1,
            "speed_mach": 4.0,
            "guidance": "imaging_IR",
            "seeker_generation": 5,
            "base_pk": 0.90,
            "warhead_kg": 11,
            "eccm_rating": 85,
            "maneuverability_g": 60,
            "cost_per_unit": 600,
        },
        {
            "name": "AIM-9X Sidewinder",
            "origin": "USA",
            "weapon_type": WeaponType.IR_AAM,
            "weight_kg": 85,
            "max_range_km": 18,
            "no_escape_range_km": 8,
            "min_range_km": 1,
            "speed_mach": 3.0,
            "guidance": "imaging_IR",
            "seeker_generation": 5,
            "base_pk": 0.88,
            "warhead_kg": 9,
            "eccm_rating": 80,
            "maneuverability_g": 55,
            "cost_per_unit": 500,
        },
        {
            "name": "MICA IR",
            "origin": "France",
            "weapon_type": WeaponType.IR_AAM,
            "weight_kg": 112,
            "max_range_km": 20,
            "no_escape_range_km": 10,
            "min_range_km": 1,
            "speed_mach": 4.0,
            "guidance": "imaging_IR",
            "seeker_generation": 4,
            "base_pk": 0.85,
            "warhead_kg": 12,
            "eccm_rating": 78,
            "maneuverability_g": 50,
            "cost_per_unit": 550,
        },
        # Anti-Ship Missiles
        {
            "name": "BrahMos",
            "origin": "India/Russia",
            "weapon_type": WeaponType.ASM,
            "weight_kg": 3000,
            "max_range_km": 290,
            "no_escape_range_km": 120,
            "min_range_km": 10,
            "speed_mach": 2.8,
            "guidance": "inertial+active_radar+GPS",
            "seeker_generation": 4,
            "base_pk": 0.85,
            "warhead_kg": 300,
            "eccm_rating": 80,
            "maneuverability_g": 15,
            "cost_per_unit": 5000,
        },
        {
            "name": "Harpoon",
            "origin": "USA",
            "weapon_type": WeaponType.ASM,
            "weight_kg": 691,
            "max_range_km": 130,
            "no_escape_range_km": 50,
            "min_range_km": 5,
            "speed_mach": 0.85,
            "guidance": "inertial+active_radar",
            "seeker_generation": 3,
            "base_pk": 0.70,
            "warhead_kg": 221,
            "eccm_rating": 60,
            "maneuverability_g": 10,
            "cost_per_unit": 3000,
        },
        {
            "name": "YJ-18",
            "origin": "China",
            "weapon_type": WeaponType.ASM,
            "weight_kg": 2000,
            "max_range_km": 220,
            "no_escape_range_km": 80,
            "min_range_km": 10,
            "speed_mach": 3.0,
            "guidance": "inertial+active_radar",
            "seeker_generation": 3,
            "base_pk": 0.78,
            "warhead_kg": 300,
            "eccm_rating": 65,
            "maneuverability_g": 12,
            "cost_per_unit": 4000,
        },
        # SAM Systems
        {
            "name": "Barak-8",
            "origin": "India/Israel",
            "weapon_type": WeaponType.SAM,
            "weight_kg": 275,
            "max_range_km": 100,
            "no_escape_range_km": 40,
            "min_range_km": 2,
            "speed_mach": 2.0,
            "guidance": "active_radar",
            "seeker_generation": 4,
            "base_pk": 0.80,
            "warhead_kg": 60,
            "eccm_rating": 78,
            "maneuverability_g": 30,
            "cost_per_unit": 2500,
        },
        {
            "name": "SM-2 Standard",
            "origin": "USA",
            "weapon_type": WeaponType.SAM,
            "weight_kg": 1558,
            "max_range_km": 170,
            "no_escape_range_km": 70,
            "min_range_km": 5,
            "speed_mach": 3.5,
            "guidance": "semi_active_radar",
            "seeker_generation": 4,
            "base_pk": 0.85,
            "warhead_kg": 115,
            "eccm_rating": 85,
            "maneuverability_g": 25,
            "cost_per_unit": 4000,
        },
        {
            "name": "HHQ-9",
            "origin": "China",
            "weapon_type": WeaponType.SAM,
            "weight_kg": 1300,
            "max_range_km": 200,
            "no_escape_range_km": 80,
            "min_range_km": 6,
            "speed_mach": 4.2,
            "guidance": "semi_active_radar+active_radar",
            "seeker_generation": 3,
            "base_pk": 0.75,
            "warhead_kg": 180,
            "eccm_rating": 65,
            "maneuverability_g": 22,
            "cost_per_unit": 3500,
        },
        # CIWS
        {
            "name": "AK-630",
            "origin": "Russia",
            "weapon_type": WeaponType.CIWS,
            "weight_kg": 9114,
            "max_range_km": 4,
            "no_escape_range_km": 2,
            "min_range_km": 0,
            "speed_mach": 0.0,
            "guidance": "radar_directed",
            "seeker_generation": 2,
            "base_pk": 0.40,
            "warhead_kg": 0,
            "eccm_rating": 30,
            "maneuverability_g": 0,
            "cost_per_unit": 1500,
        },
        {
            "name": "Phalanx CIWS",
            "origin": "USA",
            "weapon_type": WeaponType.CIWS,
            "weight_kg": 6200,
            "max_range_km": 4,
            "no_escape_range_km": 2,
            "min_range_km": 0,
            "speed_mach": 0.0,
            "guidance": "radar_directed",
            "seeker_generation": 3,
            "base_pk": 0.50,
            "warhead_kg": 0,
            "eccm_rating": 40,
            "maneuverability_g": 0,
            "cost_per_unit": 2000,
        },
    ]

    weapon_id_map = {}
    for w_data in weapons:
        existing = db.query(Weapon).filter(Weapon.name == w_data["name"]).first()
        if not existing:
            weapon = Weapon(**w_data)
            db.add(weapon)
            db.flush()
            weapon_id_map[w_data["name"]] = weapon.id
        else:
            weapon_id_map[w_data["name"]] = existing.id

    # ── AIRCRAFT ──

    aircraft_list = [
        {
            "name": "Dassault Rafale",
            "origin": "France",
            "role": "multirole",
            "generation": "4.5",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Rafale_-_RIAT_2009_%283751997379%29.jpg/1280px-Rafale_-_RIAT_2009_%283751997379%29.jpg",
            "max_speed_mach": 1.8,
            "max_speed_loaded_mach": 1.4,
            "combat_radius_km": 1850,
            "service_ceiling_ft": 50000,
            "max_g_load": 9.0,
            "thrust_to_weight_clean": 1.13,
            "wing_loading_kg_m2": 306,
            "instantaneous_turn_rate_deg_s": 28,
            "sustained_turn_rate_deg_s": 22,
            "empty_weight_kg": 10300,
            "max_takeoff_weight_kg": 24500,
            "internal_fuel_kg": 4700,
            "max_payload_kg": 9500,
            "hardpoints": 14,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("MICA EM"),
                weapon_id_map.get("MICA IR"),
                weapon_id_map.get("Meteor"),
            ]),
            "radar_type": "RBE2 AESA",
            "radar_range_km": 200,
            "rcs_m2": 1.0,
            "irst": True,
            "ecm_suite": "SPECTRA",
            "ecm_rating": 85,
            "chaff_count": 112,
            "flare_count": 32,
            "towed_decoy": True,
            "unlock_cost": 120000,
            "maintenance_cost": 8000,
        },
        {
            "name": "F-16C Block 52",
            "origin": "USA",
            "role": "multirole",
            "generation": "4",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/F-16_June_2008.jpg/1280px-F-16_June_2008.jpg",
            "max_speed_mach": 2.0,
            "max_speed_loaded_mach": 1.5,
            "combat_radius_km": 1370,
            "service_ceiling_ft": 50000,
            "max_g_load": 9.0,
            "thrust_to_weight_clean": 1.095,
            "wing_loading_kg_m2": 431,
            "instantaneous_turn_rate_deg_s": 26,
            "sustained_turn_rate_deg_s": 20,
            "empty_weight_kg": 8570,
            "max_takeoff_weight_kg": 19200,
            "internal_fuel_kg": 3160,
            "max_payload_kg": 7700,
            "hardpoints": 11,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("AIM-120C AMRAAM"),
                weapon_id_map.get("AIM-9X Sidewinder"),
            ]),
            "radar_type": "APG-68(V)9",
            "radar_range_km": 160,
            "rcs_m2": 5.0,
            "irst": False,
            "ecm_suite": "ALQ-211 AIDEWS",
            "ecm_rating": 65,
            "chaff_count": 90,
            "flare_count": 30,
            "towed_decoy": False,
            "unlock_cost": 80000,
            "maintenance_cost": 5000,
        },
        {
            "name": "Su-30MKI",
            "origin": "Russia/India",
            "role": "air_superiority",
            "generation": "4.5",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Su-30MKI_Lajes.jpg/1280px-Su-30MKI_Lajes.jpg",
            "max_speed_mach": 2.0,
            "max_speed_loaded_mach": 1.5,
            "combat_radius_km": 1800,
            "service_ceiling_ft": 56800,
            "max_g_load": 9.0,
            "thrust_to_weight_clean": 1.0,
            "wing_loading_kg_m2": 401,
            "instantaneous_turn_rate_deg_s": 27,
            "sustained_turn_rate_deg_s": 21,
            "empty_weight_kg": 18400,
            "max_takeoff_weight_kg": 38800,
            "internal_fuel_kg": 9640,
            "max_payload_kg": 12000,
            "hardpoints": 12,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("R-77"),
                weapon_id_map.get("Astra Mk-1"),
                weapon_id_map.get("Astra Mk-2"),
            ]),
            "radar_type": "N011M BARS PESA",
            "radar_range_km": 200,
            "rcs_m2": 10.0,
            "irst": True,
            "ecm_suite": "Tarang Mk2",
            "ecm_rating": 60,
            "chaff_count": 96,
            "flare_count": 48,
            "towed_decoy": False,
            "unlock_cost": 100000,
            "maintenance_cost": 7000,
        },
        {
            "name": "F-15E Strike Eagle",
            "origin": "USA",
            "role": "air_superiority",
            "generation": "4",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/F-15E_on_patrol.jpg/1280px-F-15E_on_patrol.jpg",
            "max_speed_mach": 2.5,
            "max_speed_loaded_mach": 1.8,
            "combat_radius_km": 1270,
            "service_ceiling_ft": 60000,
            "max_g_load": 9.0,
            "thrust_to_weight_clean": 1.12,
            "wing_loading_kg_m2": 358,
            "instantaneous_turn_rate_deg_s": 25,
            "sustained_turn_rate_deg_s": 19,
            "empty_weight_kg": 14300,
            "max_takeoff_weight_kg": 36700,
            "internal_fuel_kg": 6100,
            "max_payload_kg": 11000,
            "hardpoints": 15,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("AIM-120C AMRAAM"),
                weapon_id_map.get("AIM-9X Sidewinder"),
            ]),
            "radar_type": "APG-82(V)1 AESA",
            "radar_range_km": 180,
            "rcs_m2": 10.0,
            "irst": False,
            "ecm_suite": "TEWS",
            "ecm_rating": 70,
            "chaff_count": 120,
            "flare_count": 60,
            "towed_decoy": True,
            "unlock_cost": 110000,
            "maintenance_cost": 7500,
        },
        {
            "name": "JF-17 Thunder",
            "origin": "Pakistan/China",
            "role": "multirole",
            "generation": "4",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Pakistan_Air_Force_JF-17.jpg/1280px-Pakistan_Air_Force_JF-17.jpg",
            "max_speed_mach": 1.6,
            "max_speed_loaded_mach": 1.2,
            "combat_radius_km": 1352,
            "service_ceiling_ft": 55000,
            "max_g_load": 8.5,
            "thrust_to_weight_clean": 0.95,
            "wing_loading_kg_m2": 372,
            "instantaneous_turn_rate_deg_s": 22,
            "sustained_turn_rate_deg_s": 17,
            "empty_weight_kg": 6586,
            "max_takeoff_weight_kg": 12700,
            "internal_fuel_kg": 2330,
            "max_payload_kg": 3800,
            "hardpoints": 7,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("R-77"),
            ]),
            "radar_type": "KLJ-7A AESA",
            "radar_range_km": 130,
            "rcs_m2": 3.0,
            "irst": False,
            "ecm_suite": "Basic ECM",
            "ecm_rating": 40,
            "chaff_count": 64,
            "flare_count": 24,
            "towed_decoy": False,
            "unlock_cost": 40000,
            "maintenance_cost": 2500,
        },
        {
            "name": "Tejas Mk2",
            "origin": "India",
            "role": "multirole",
            "generation": "4.5",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/HAL_Tejas_NP-1_takes_off_for_a_test_flight.jpg/1280px-HAL_Tejas_NP-1_takes_off_for_a_test_flight.jpg",
            "max_speed_mach": 1.8,
            "max_speed_loaded_mach": 1.4,
            "combat_radius_km": 1500,
            "service_ceiling_ft": 50000,
            "max_g_load": 8.0,
            "thrust_to_weight_clean": 1.07,
            "wing_loading_kg_m2": 295,
            "instantaneous_turn_rate_deg_s": 25,
            "sustained_turn_rate_deg_s": 20,
            "empty_weight_kg": 7500,
            "max_takeoff_weight_kg": 17500,
            "internal_fuel_kg": 3400,
            "max_payload_kg": 6500,
            "hardpoints": 11,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("Astra Mk-1"),
                weapon_id_map.get("Astra Mk-2"),
                weapon_id_map.get("Python-5"),
            ]),
            "radar_type": "Uttam AESA",
            "radar_range_km": 150,
            "rcs_m2": 1.5,
            "irst": True,
            "ecm_suite": "Mayavi",
            "ecm_rating": 70,
            "chaff_count": 80,
            "flare_count": 32,
            "towed_decoy": True,
            "unlock_cost": 60000,
            "maintenance_cost": 3500,
        },
        {
            "name": "Mirage 2000-5",
            "origin": "France",
            "role": "multirole",
            "generation": "4",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Mirage_2000C_in-flight.jpg/1280px-Mirage_2000C_in-flight.jpg",
            "max_speed_mach": 2.2,
            "max_speed_loaded_mach": 1.6,
            "combat_radius_km": 1550,
            "service_ceiling_ft": 59000,
            "max_g_load": 9.0,
            "thrust_to_weight_clean": 1.05,
            "wing_loading_kg_m2": 337,
            "instantaneous_turn_rate_deg_s": 26,
            "sustained_turn_rate_deg_s": 21,
            "empty_weight_kg": 7500,
            "max_takeoff_weight_kg": 17460,
            "internal_fuel_kg": 3160,
            "max_payload_kg": 6300,
            "hardpoints": 9,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("MICA EM"),
                weapon_id_map.get("MICA IR"),
            ]),
            "radar_type": "RDY-2",
            "radar_range_km": 150,
            "rcs_m2": 2.0,
            "irst": False,
            "ecm_suite": "ICMS Mk3",
            "ecm_rating": 60,
            "chaff_count": 96,
            "flare_count": 32,
            "towed_decoy": False,
            "unlock_cost": 65000,
            "maintenance_cost": 4000,
        },
        {
            "name": "Eurofighter Typhoon",
            "origin": "Europe",
            "role": "air_superiority",
            "generation": "4.5",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Eurofighter_Typhoon_1.jpg/1280px-Eurofighter_Typhoon_1.jpg",
            "max_speed_mach": 2.0,
            "max_speed_loaded_mach": 1.5,
            "combat_radius_km": 1390,
            "service_ceiling_ft": 65000,
            "max_g_load": 9.0,
            "thrust_to_weight_clean": 1.18,
            "wing_loading_kg_m2": 312,
            "instantaneous_turn_rate_deg_s": 29,
            "sustained_turn_rate_deg_s": 23,
            "empty_weight_kg": 11000,
            "max_takeoff_weight_kg": 23500,
            "internal_fuel_kg": 5000,
            "max_payload_kg": 9000,
            "hardpoints": 13,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("Meteor"),
                weapon_id_map.get("AIM-120C AMRAAM"),
                weapon_id_map.get("AIM-9X Sidewinder"),
            ]),
            "radar_type": "Captor-E AESA",
            "radar_range_km": 200,
            "rcs_m2": 0.5,
            "irst": True,
            "ecm_suite": "Praetorian DASS",
            "ecm_rating": 88,
            "chaff_count": 120,
            "flare_count": 48,
            "towed_decoy": True,
            "unlock_cost": 130000,
            "maintenance_cost": 9000,
        },
    ]

    for a_data in aircraft_list:
        existing = db.query(Aircraft).filter(Aircraft.name == a_data["name"]).first()
        if not existing:
            db.add(Aircraft(**a_data))

    # ── SHIPS ──

    ships = [
        {
            "name": "INS Chennai",
            "class_name": "Kolkata",
            "origin": "India",
            "ship_type": ShipType.DESTROYER,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/INS_Chennai_%28D65%29.jpg/1280px-INS_Chennai_%28D65%29.jpg",
            "displacement_tons": 7500,
            "max_speed_knots": 30,
            "crew": 300,
            "radar_type": "MF-STAR AESA",
            "radar_range_km": 250,
            "sonar": "HUMSA-NG",
            "helicopter": "Sea King Mk42B",
            "anti_ship_missiles": json.dumps([{"weapon_id": weapon_id_map.get("BrahMos"), "count": 16}]),
            "sam_systems": json.dumps([{"weapon_id": weapon_id_map.get("Barak-8"), "count": 32}]),
            "ciws": json.dumps([{"weapon_id": weapon_id_map.get("AK-630"), "count": 2}]),
            "torpedoes": json.dumps([]),
            "gun": "OTO Melara 76mm Super Rapid",
            "ecm_suite": "Ajanta Mk2",
            "ecm_rating": 75,
            "decoys": "Kavach",
            "compartments": 15,
            "unlock_cost": 500000,
            "maintenance_cost": 25000,
        },
        {
            "name": "INS Visakhapatnam",
            "class_name": "Visakhapatnam",
            "origin": "India",
            "ship_type": ShipType.DESTROYER,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/INS_Visakhapatnam_%28D66%29_during_sea_trials.jpg/1280px-INS_Visakhapatnam_%28D66%29_during_sea_trials.jpg",
            "displacement_tons": 7400,
            "max_speed_knots": 30,
            "crew": 310,
            "radar_type": "MF-STAR AESA (upgraded)",
            "radar_range_km": 270,
            "sonar": "HUMSA-NG",
            "helicopter": "MH-60R",
            "anti_ship_missiles": json.dumps([{"weapon_id": weapon_id_map.get("BrahMos"), "count": 8}]),
            "sam_systems": json.dumps([{"weapon_id": weapon_id_map.get("Barak-8"), "count": 32}]),
            "ciws": json.dumps([{"weapon_id": weapon_id_map.get("AK-630"), "count": 4}]),
            "torpedoes": json.dumps([]),
            "gun": "OTO Melara 76mm Super Rapid",
            "ecm_suite": "Ajanta Mk2E",
            "ecm_rating": 78,
            "decoys": "Kavach Mk2",
            "compartments": 16,
            "unlock_cost": 520000,
            "maintenance_cost": 26000,
        },
        {
            "name": "Type 052D Kunming",
            "class_name": "Luyang III",
            "origin": "China",
            "ship_type": ShipType.DESTROYER,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/CNS_Kunming_%28DDG-172%29_20190424.jpg/1280px-CNS_Kunming_%28DDG-172%29_20190424.jpg",
            "displacement_tons": 7500,
            "max_speed_knots": 29,
            "crew": 280,
            "radar_type": "Type 346A AESA",
            "radar_range_km": 300,
            "sonar": "MGK-335",
            "helicopter": "Ka-28",
            "anti_ship_missiles": json.dumps([{"weapon_id": weapon_id_map.get("YJ-18"), "count": 8}]),
            "sam_systems": json.dumps([{"weapon_id": weapon_id_map.get("HHQ-9"), "count": 64}]),
            "ciws": json.dumps([{"weapon_id": weapon_id_map.get("Phalanx CIWS"), "count": 1}]),
            "torpedoes": json.dumps([]),
            "gun": "H/PJ-45 130mm",
            "ecm_suite": "Type 726-4",
            "ecm_rating": 68,
            "decoys": "Type 726 decoy launcher",
            "compartments": 14,
            "unlock_cost": 480000,
            "maintenance_cost": 24000,
        },
        {
            "name": "USS Arleigh Burke IIA",
            "class_name": "Arleigh Burke",
            "origin": "USA",
            "ship_type": ShipType.DESTROYER,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/USS_Arleigh_Burke_%28DDG-51%29_underway_in_the_Atlantic_Ocean_on_22_September_2017.jpg/1280px-USS_Arleigh_Burke_%28DDG-51%29_underway_in_the_Atlantic_Ocean_on_22_September_2017.jpg",
            "displacement_tons": 9200,
            "max_speed_knots": 31,
            "crew": 323,
            "radar_type": "AN/SPY-1D(V) PESA",
            "radar_range_km": 320,
            "sonar": "AN/SQQ-89",
            "helicopter": "MH-60R Seahawk",
            "anti_ship_missiles": json.dumps([{"weapon_id": weapon_id_map.get("Harpoon"), "count": 8}]),
            "sam_systems": json.dumps([{"weapon_id": weapon_id_map.get("SM-2 Standard"), "count": 96}]),
            "ciws": json.dumps([{"weapon_id": weapon_id_map.get("Phalanx CIWS"), "count": 2}]),
            "torpedoes": json.dumps([]),
            "gun": "Mk 45 5-inch/127mm",
            "ecm_suite": "AN/SLQ-32(V)3",
            "ecm_rating": 82,
            "decoys": "Mk 36 SRBOC",
            "compartments": 18,
            "unlock_cost": 600000,
            "maintenance_cost": 30000,
        },
        {
            "name": "Admiral Gorshkov",
            "class_name": "Gorshkov",
            "origin": "Russia",
            "ship_type": ShipType.FRIGATE,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Admiral_Gorshkov_frigate_02.jpg/1280px-Admiral_Gorshkov_frigate_02.jpg",
            "displacement_tons": 5400,
            "max_speed_knots": 30,
            "crew": 210,
            "radar_type": "Poliment-Redut AESA",
            "radar_range_km": 200,
            "sonar": "Zarya-2",
            "helicopter": "Ka-27",
            "anti_ship_missiles": json.dumps([{"weapon_id": weapon_id_map.get("BrahMos"), "count": 16}]),
            "sam_systems": json.dumps([{"weapon_id": weapon_id_map.get("Barak-8"), "count": 32}]),
            "ciws": json.dumps([{"weapon_id": weapon_id_map.get("AK-630"), "count": 2}]),
            "torpedoes": json.dumps([]),
            "gun": "A-192M 130mm",
            "ecm_suite": "5P-10 Puma",
            "ecm_rating": 70,
            "decoys": "PK-10 Smerch",
            "compartments": 12,
            "unlock_cost": 350000,
            "maintenance_cost": 18000,
        },
    ]

    for s_data in ships:
        existing = db.query(Ship).filter(Ship.name == s_data["name"]).first()
        if not existing:
            db.add(Ship(**s_data))

    db.commit()

    # ── BATTLE-TYPE MISSION TEMPLATES ──

    from app.models.contract import MissionTemplate, Faction

    # Look up aircraft/ship IDs by name
    def get_ac_id(name):
        ac = db.query(Aircraft).filter(Aircraft.name == name).first()
        return ac.id if ac else None

    def get_ship_id(name):
        s = db.query(Ship).filter(Ship.name == name).first()
        return s.id if s else None

    battle_missions = [
        {
            "title": "Air Superiority: Rafale vs F-16",
            "description": "Intercept and engage an F-16C Block 52 operating in contested airspace. BVR engagement expected.",
            "faction": Faction.ATLANTIC_COALITION,
            "required_unit_types": '["fighter"]',
            "base_payout": 35000,
            "risk_level": 55,
            "political_impact": 10,
            "estimated_duration_hours": 4,
            "battle_type": "air",
            "enemy_aircraft_id": get_ac_id("F-16C Block 52"),
        },
        {
            "title": "Dogfight: Typhoon vs Su-30MKI",
            "description": "Engage a Su-30MKI Flanker in a head-on BVR duel over open waters. The Flanker is heavily armed.",
            "faction": Faction.DESERT_BLOC,
            "required_unit_types": '["fighter"]',
            "base_payout": 45000,
            "risk_level": 70,
            "political_impact": -10,
            "estimated_duration_hours": 4,
            "battle_type": "air",
            "enemy_aircraft_id": get_ac_id("Su-30MKI"),
        },
        {
            "title": "Naval Interdiction: Chennai vs Type 052D",
            "description": "Engage a Chinese Type 052D destroyer threatening allied shipping lanes. Expect heavy SAM defense.",
            "faction": Faction.PACIFIC_ALLIANCE,
            "required_unit_types": '["destroyer"]',
            "base_payout": 50000,
            "risk_level": 65,
            "political_impact": 15,
            "estimated_duration_hours": 8,
            "battle_type": "naval",
            "enemy_ship_id": get_ship_id("Type 052D Kunming"),
        },
        {
            "title": "Surface Duel: Gorshkov vs Burke",
            "description": "An Arleigh Burke destroyer has been detected. Engage with BrahMos anti-ship missiles.",
            "faction": Faction.SAHARA_SINDICATE,
            "required_unit_types": '["frigate"]',
            "base_payout": 55000,
            "risk_level": 75,
            "political_impact": -15,
            "estimated_duration_hours": 8,
            "battle_type": "naval",
            "enemy_ship_id": get_ship_id("USS Arleigh Burke IIA"),
        },
    ]

    for m_data in battle_missions:
        existing = db.query(MissionTemplate).filter(MissionTemplate.title == m_data["title"]).first()
        if not existing:
            db.add(MissionTemplate(**m_data))

    db.commit()

    # ── STARTING OWNED AIRCRAFT & SHIP FOR DEFAULT USER ──

    from app.models.owned_aircraft import OwnedAircraft
    from app.models.owned_ship import OwnedShip
    from app.models.user import User

    user = db.query(User).filter(User.username == "commander").first()
    if user:
        # Give starting aircraft if none owned
        existing_ac = db.query(OwnedAircraft).filter(OwnedAircraft.user_id == user.id).count()
        if existing_ac == 0:
            rafale_id = get_ac_id("Dassault Rafale")
            if rafale_id:
                db.add(OwnedAircraft(user_id=user.id, aircraft_id=rafale_id, condition=100))

        # Give starting ship if none owned
        existing_ship = db.query(OwnedShip).filter(OwnedShip.user_id == user.id).count()
        if existing_ship == 0:
            chennai_id = get_ship_id("INS Chennai")
            if chennai_id:
                db.add(OwnedShip(user_id=user.id, ship_id=chennai_id, condition=100))

        db.commit()
