import json
from sqlalchemy.orm import Session
from app.models.aircraft import Aircraft
from app.models.weapon import Weapon, WeaponType
from app.models.ship import Ship, ShipType


def seed_hardware(db: Session) -> None:
    """Seed the database with real military hardware data."""

    # ── WEAPONS (must be seeded first, aircraft reference weapon IDs) ──

    weapons = [
        # BVR Air-to-Air Missiles
        {
            "name": "Astra Mk-1",
            "origin": "India",
            "weapon_type": WeaponType.BVR_AAM,
            "weight_kg": 154,
            "max_range_km": 110,
            "no_escape_range_km": 35,
            "min_range_km": 5,
            "speed_mach": 4.0,
            "guidance": "inertial+active_radar",
            "seeker_generation": 3,
            "base_pk": 0.70,
            "warhead_kg": 15,
            "eccm_rating": 65,
            "maneuverability_g": 35,
            "cost_per_unit": 800,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/55/AstraMk1Missile.jpg",
        },
        {
            "name": "Astra Mk-2",
            "origin": "India",
            "weapon_type": WeaponType.BVR_AAM,
            "weight_kg": 160,
            "max_range_km": 160,
            "no_escape_range_km": 60,
            "min_range_km": 5,
            "speed_mach": 4.5,
            "guidance": "inertial+active_radar",
            "seeker_generation": 4,
            "base_pk": 0.75,
            "warhead_kg": 15,
            "eccm_rating": 75,
            "maneuverability_g": 40,
            "cost_per_unit": 1200,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/c/cb/Astra_missile_launched_from_a_ground-based_launcher.jpg",
        },
        {
            "name": "AIM-120C AMRAAM",
            "origin": "USA",
            "weapon_type": WeaponType.BVR_AAM,
            "weight_kg": 152,
            "max_range_km": 120,
            "no_escape_range_km": 45,
            "min_range_km": 4,
            "speed_mach": 4.0,
            "guidance": "inertial+active_radar",
            "seeker_generation": 4,
            "base_pk": 0.80,
            "warhead_kg": 18,
            "eccm_rating": 80,
            "maneuverability_g": 40,
            "cost_per_unit": 1100,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/d7/AIM-120_AMRAAM_P6230147.JPG",
        },
        {
            "name": "MICA EM",
            "origin": "France",
            "weapon_type": WeaponType.BVR_AAM,
            "weight_kg": 112,
            "max_range_km": 80,
            "no_escape_range_km": 30,
            "min_range_km": 3,
            "speed_mach": 4.0,
            "guidance": "inertial+active_radar",
            "seeker_generation": 4,
            "base_pk": 0.85,
            "warhead_kg": 12,
            "eccm_rating": 82,
            "maneuverability_g": 50,
            "cost_per_unit": 1000,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/d5/MICA_P6230072.JPG",
        },
        {
            "name": "Meteor",
            "origin": "Europe",
            "weapon_type": WeaponType.BVR_AAM,
            "weight_kg": 190,
            "max_range_km": 200,
            "no_escape_range_km": 80,
            "min_range_km": 5,
            "speed_mach": 4.5,
            "guidance": "inertial+active_radar",
            "seeker_generation": 5,
            "base_pk": 0.90,
            "warhead_kg": 25,
            "eccm_rating": 90,
            "maneuverability_g": 45,
            "cost_per_unit": 2000,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Meteor_Missile_in_EuroFighter.JPG",
        },
        {
            "name": "R-77",
            "origin": "Russia",
            "weapon_type": WeaponType.BVR_AAM,
            "weight_kg": 175,
            "max_range_km": 110,
            "no_escape_range_km": 40,
            "min_range_km": 5,
            "speed_mach": 4.0,
            "guidance": "inertial+active_radar",
            "seeker_generation": 3,
            "base_pk": 0.70,
            "warhead_kg": 22,
            "eccm_rating": 60,
            "maneuverability_g": 35,
            "cost_per_unit": 700,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Vympel-R-77-maks2009.jpg",
        },
        # IR Air-to-Air Missiles (WVR)
        {
            "name": "Python-5",
            "origin": "Israel",
            "weapon_type": WeaponType.IR_AAM,
            "weight_kg": 105,
            "max_range_km": 20,
            "no_escape_range_km": 10,
            "min_range_km": 1,
            "speed_mach": 4.0,
            "guidance": "imaging_IR",
            "seeker_generation": 5,
            "base_pk": 0.90,
            "warhead_kg": 11,
            "eccm_rating": 85,
            "maneuverability_g": 60,
            "cost_per_unit": 600,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Python5-missile001.jpg",
        },
        {
            "name": "AIM-9X Sidewinder",
            "origin": "USA",
            "weapon_type": WeaponType.IR_AAM,
            "weight_kg": 85,
            "max_range_km": 18,
            "no_escape_range_km": 8,
            "min_range_km": 1,
            "speed_mach": 3.0,
            "guidance": "imaging_IR",
            "seeker_generation": 5,
            "base_pk": 0.88,
            "warhead_kg": 9,
            "eccm_rating": 80,
            "maneuverability_g": 55,
            "cost_per_unit": 500,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/f/f8/AIM-9X_F-15C_2002.JPEG",
        },
        {
            "name": "MICA IR",
            "origin": "France",
            "weapon_type": WeaponType.IR_AAM,
            "weight_kg": 112,
            "max_range_km": 20,
            "no_escape_range_km": 10,
            "min_range_km": 1,
            "speed_mach": 4.0,
            "guidance": "imaging_IR",
            "seeker_generation": 4,
            "base_pk": 0.85,
            "warhead_kg": 12,
            "eccm_rating": 78,
            "maneuverability_g": 50,
            "cost_per_unit": 550,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/d5/MICA_P6230072.JPG",
        },
        # Anti-Ship Missiles
        {
            "name": "BrahMos",
            "origin": "India/Russia",
            "weapon_type": WeaponType.ASM,
            "weight_kg": 3000,
            "max_range_km": 290,
            "no_escape_range_km": 120,
            "min_range_km": 10,
            "speed_mach": 2.8,
            "guidance": "inertial+active_radar+GPS",
            "seeker_generation": 4,
            "base_pk": 0.85,
            "warhead_kg": 300,
            "eccm_rating": 80,
            "maneuverability_g": 15,
            "cost_per_unit": 5000,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/9/90/BRAHMOS_Launcher.JPG",
        },
        {
            "name": "Harpoon",
            "origin": "USA",
            "weapon_type": WeaponType.ASM,
            "weight_kg": 691,
            "max_range_km": 130,
            "no_escape_range_km": 50,
            "min_range_km": 5,
            "speed_mach": 0.85,
            "guidance": "inertial+active_radar",
            "seeker_generation": 3,
            "base_pk": 0.70,
            "warhead_kg": 221,
            "eccm_rating": 60,
            "maneuverability_g": 10,
            "cost_per_unit": 3000,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Mk_141_Harpoon_Missile_Launcher.JPG",
        },
        {
            "name": "YJ-18",
            "origin": "China",
            "weapon_type": WeaponType.ASM,
            "weight_kg": 2000,
            "max_range_km": 220,
            "no_escape_range_km": 80,
            "min_range_km": 10,
            "speed_mach": 3.0,
            "guidance": "inertial+active_radar",
            "seeker_generation": 3,
            "base_pk": 0.78,
            "warhead_kg": 300,
            "eccm_rating": 65,
            "maneuverability_g": 12,
            "cost_per_unit": 4000,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/d7/YJ-83J_Missile_20170902.jpg",
        },
        # SAM Systems
        {
            "name": "Barak-8",
            "origin": "India/Israel",
            "weapon_type": WeaponType.SAM,
            "weight_kg": 275,
            "max_range_km": 100,
            "no_escape_range_km": 40,
            "min_range_km": 2,
            "speed_mach": 2.0,
            "guidance": "active_radar",
            "seeker_generation": 4,
            "base_pk": 0.80,
            "warhead_kg": 60,
            "eccm_rating": 78,
            "maneuverability_g": 30,
            "cost_per_unit": 2500,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/10/Barak_8_launcher.jpg",
        },
        {
            "name": "SM-2 Standard",
            "origin": "USA",
            "weapon_type": WeaponType.SAM,
            "weight_kg": 1558,
            "max_range_km": 170,
            "no_escape_range_km": 70,
            "min_range_km": 5,
            "speed_mach": 3.5,
            "guidance": "semi_active_radar",
            "seeker_generation": 4,
            "base_pk": 0.85,
            "warhead_kg": 115,
            "eccm_rating": 85,
            "maneuverability_g": 25,
            "cost_per_unit": 4000,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/2/28/Sm-2.JPG",
        },
        {
            "name": "HHQ-9",
            "origin": "China",
            "weapon_type": WeaponType.SAM,
            "weight_kg": 1300,
            "max_range_km": 200,
            "no_escape_range_km": 80,
            "min_range_km": 6,
            "speed_mach": 4.2,
            "guidance": "semi_active_radar+active_radar",
            "seeker_generation": 3,
            "base_pk": 0.75,
            "warhead_kg": 180,
            "eccm_rating": 65,
            "maneuverability_g": 22,
            "cost_per_unit": 3500,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/d0/Chinese_HQ-9_launcher.jpg",
        },
        # CIWS
        {
            "name": "AK-630",
            "origin": "Russia",
            "weapon_type": WeaponType.CIWS,
            "weight_kg": 9114,
            "max_range_km": 4,
            "no_escape_range_km": 2,
            "min_range_km": 0,
            "speed_mach": 0.0,
            "guidance": "radar_directed",
            "seeker_generation": 2,
            "base_pk": 0.40,
            "warhead_kg": 0,
            "eccm_rating": 30,
            "maneuverability_g": 0,
            "cost_per_unit": 1500,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/80/AK-630_30_mm_naval_CIWS_gun.JPEG",
        },
        {
            "name": "Phalanx CIWS",
            "origin": "USA",
            "weapon_type": WeaponType.CIWS,
            "weight_kg": 6200,
            "max_range_km": 4,
            "no_escape_range_km": 2,
            "min_range_km": 0,
            "speed_mach": 0.0,
            "guidance": "radar_directed",
            "seeker_generation": 3,
            "base_pk": 0.50,
            "warhead_kg": 0,
            "eccm_rating": 40,
            "maneuverability_g": 0,
            "cost_per_unit": 2000,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Phalanx_CIWS_-_Side_View.JPG",
        },
    ]

    weapon_id_map = {}
    for w_data in weapons:
        existing = db.query(Weapon).filter(Weapon.name == w_data["name"]).first()
        if not existing:
            weapon = Weapon(**w_data)
            db.add(weapon)
            db.flush()
            weapon_id_map[w_data["name"]] = weapon.id
        else:
            weapon_id_map[w_data["name"]] = existing.id

    # ── AIRCRAFT ──

    aircraft_list = [
        {
            "name": "Dassault Rafale",
            "origin": "France",
            "role": "multirole",
            "generation": "4.5",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/2/28/Dassault_Rafale_DSC04183.JPG",
            "max_speed_mach": 1.8,
            "max_speed_loaded_mach": 1.4,
            "combat_radius_km": 1850,
            "service_ceiling_ft": 50000,
            "max_g_load": 9.0,
            "thrust_to_weight_clean": 1.13,
            "wing_loading_kg_m2": 306,
            "instantaneous_turn_rate_deg_s": 28,
            "sustained_turn_rate_deg_s": 22,
            "empty_weight_kg": 10300,
            "max_takeoff_weight_kg": 24500,
            "internal_fuel_kg": 4700,
            "max_payload_kg": 9500,
            "hardpoints": 14,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("MICA EM"),
                weapon_id_map.get("MICA IR"),
                weapon_id_map.get("Meteor"),
            ]),
            "radar_type": "RBE2 AESA",
            "radar_range_km": 200,
            "rcs_m2": 1.0,
            "irst": True,
            "ecm_suite": "SPECTRA",
            "ecm_rating": 85,
            "chaff_count": 112,
            "flare_count": 32,
            "towed_decoy": True,
            "unlock_cost": 120000,
            "maintenance_cost": 8000,
        },
        {
            "name": "F-16C Block 52",
            "origin": "USA",
            "role": "multirole",
            "generation": "4",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/bf/F-16C_Fighting_Falcon.JPEG",
            "max_speed_mach": 2.0,
            "max_speed_loaded_mach": 1.5,
            "combat_radius_km": 1370,
            "service_ceiling_ft": 50000,
            "max_g_load": 9.0,
            "thrust_to_weight_clean": 1.095,
            "wing_loading_kg_m2": 431,
            "instantaneous_turn_rate_deg_s": 26,
            "sustained_turn_rate_deg_s": 20,
            "empty_weight_kg": 8570,
            "max_takeoff_weight_kg": 19200,
            "internal_fuel_kg": 3160,
            "max_payload_kg": 7700,
            "hardpoints": 11,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("AIM-120C AMRAAM"),
                weapon_id_map.get("AIM-9X Sidewinder"),
            ]),
            "radar_type": "APG-68(V)9",
            "radar_range_km": 160,
            "rcs_m2": 5.0,
            "irst": False,
            "ecm_suite": "ALQ-211 AIDEWS",
            "ecm_rating": 65,
            "chaff_count": 90,
            "flare_count": 30,
            "towed_decoy": False,
            "unlock_cost": 80000,
            "maintenance_cost": 5000,
        },
        {
            "name": "Su-30MKI",
            "origin": "Russia/India",
            "role": "air_superiority",
            "generation": "4.5",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/c/c3/230120_Indian_Air_Force_SU-30_landing_at_Hyakuri_Air_Base.jpg",
            "max_speed_mach": 2.0,
            "max_speed_loaded_mach": 1.5,
            "combat_radius_km": 1800,
            "service_ceiling_ft": 56800,
            "max_g_load": 9.0,
            "thrust_to_weight_clean": 1.0,
            "wing_loading_kg_m2": 401,
            "instantaneous_turn_rate_deg_s": 27,
            "sustained_turn_rate_deg_s": 21,
            "empty_weight_kg": 18400,
            "max_takeoff_weight_kg": 38800,
            "internal_fuel_kg": 9640,
            "max_payload_kg": 12000,
            "hardpoints": 12,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("R-77"),
                weapon_id_map.get("Astra Mk-1"),
                weapon_id_map.get("Astra Mk-2"),
            ]),
            "radar_type": "N011M BARS PESA",
            "radar_range_km": 200,
            "rcs_m2": 10.0,
            "irst": True,
            "ecm_suite": "Tarang Mk2",
            "ecm_rating": 60,
            "chaff_count": 96,
            "flare_count": 48,
            "towed_decoy": False,
            "unlock_cost": 100000,
            "maintenance_cost": 7000,
        },
        {
            "name": "F-15E Strike Eagle",
            "origin": "USA",
            "role": "air_superiority",
            "generation": "4",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/7/7f/060801-F-2907c-099_F-15E_Strike_Eagle.JPG",
            "max_speed_mach": 2.5,
            "max_speed_loaded_mach": 1.8,
            "combat_radius_km": 1270,
            "service_ceiling_ft": 60000,
            "max_g_load": 9.0,
            "thrust_to_weight_clean": 1.12,
            "wing_loading_kg_m2": 358,
            "instantaneous_turn_rate_deg_s": 25,
            "sustained_turn_rate_deg_s": 19,
            "empty_weight_kg": 14300,
            "max_takeoff_weight_kg": 36700,
            "internal_fuel_kg": 6100,
            "max_payload_kg": 11000,
            "hardpoints": 15,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("AIM-120C AMRAAM"),
                weapon_id_map.get("AIM-9X Sidewinder"),
            ]),
            "radar_type": "APG-82(V)1 AESA",
            "radar_range_km": 180,
            "rcs_m2": 10.0,
            "irst": False,
            "ecm_suite": "TEWS",
            "ecm_rating": 70,
            "chaff_count": 120,
            "flare_count": 60,
            "towed_decoy": True,
            "unlock_cost": 110000,
            "maintenance_cost": 7500,
        },
        {
            "name": "JF-17 Thunder",
            "origin": "Pakistan/China",
            "role": "multirole",
            "generation": "4",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/4/4d/Black_Panther_JF-17.jpg",
            "max_speed_mach": 1.6,
            "max_speed_loaded_mach": 1.2,
            "combat_radius_km": 1352,
            "service_ceiling_ft": 55000,
            "max_g_load": 8.5,
            "thrust_to_weight_clean": 0.95,
            "wing_loading_kg_m2": 372,
            "instantaneous_turn_rate_deg_s": 22,
            "sustained_turn_rate_deg_s": 17,
            "empty_weight_kg": 6586,
            "max_takeoff_weight_kg": 12700,
            "internal_fuel_kg": 2330,
            "max_payload_kg": 3800,
            "hardpoints": 7,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("R-77"),
            ]),
            "radar_type": "KLJ-7A AESA",
            "radar_range_km": 130,
            "rcs_m2": 3.0,
            "irst": False,
            "ecm_suite": "Basic ECM",
            "ecm_rating": 40,
            "chaff_count": 64,
            "flare_count": 24,
            "towed_decoy": False,
            "unlock_cost": 40000,
            "maintenance_cost": 2500,
        },
        {
            "name": "Tejas Mk2",
            "origin": "India",
            "role": "multirole",
            "generation": "4.5",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/3/37/HAL_Tejas_NP-1_takes-off_from_the_Shore_Based_Test_Facility_at_INS_Hansa%2C_Goa.JPG",
            "max_speed_mach": 1.8,
            "max_speed_loaded_mach": 1.4,
            "combat_radius_km": 1500,
            "service_ceiling_ft": 50000,
            "max_g_load": 8.0,
            "thrust_to_weight_clean": 1.07,
            "wing_loading_kg_m2": 295,
            "instantaneous_turn_rate_deg_s": 25,
            "sustained_turn_rate_deg_s": 20,
            "empty_weight_kg": 7500,
            "max_takeoff_weight_kg": 17500,
            "internal_fuel_kg": 3400,
            "max_payload_kg": 6500,
            "hardpoints": 11,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("Astra Mk-1"),
                weapon_id_map.get("Astra Mk-2"),
                weapon_id_map.get("Python-5"),
            ]),
            "radar_type": "Uttam AESA",
            "radar_range_km": 150,
            "rcs_m2": 1.5,
            "irst": True,
            "ecm_suite": "Mayavi",
            "ecm_rating": 70,
            "chaff_count": 80,
            "flare_count": 32,
            "towed_decoy": True,
            "unlock_cost": 60000,
            "maintenance_cost": 3500,
        },
        {
            "name": "Mirage 2000-5",
            "origin": "France",
            "role": "multirole",
            "generation": "4",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/b6/French_Mirage_2000_aircraft.JPEG",
            "max_speed_mach": 2.2,
            "max_speed_loaded_mach": 1.6,
            "combat_radius_km": 1550,
            "service_ceiling_ft": 59000,
            "max_g_load": 9.0,
            "thrust_to_weight_clean": 1.05,
            "wing_loading_kg_m2": 337,
            "instantaneous_turn_rate_deg_s": 26,
            "sustained_turn_rate_deg_s": 21,
            "empty_weight_kg": 7500,
            "max_takeoff_weight_kg": 17460,
            "internal_fuel_kg": 3160,
            "max_payload_kg": 6300,
            "hardpoints": 9,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("MICA EM"),
                weapon_id_map.get("MICA IR"),
            ]),
            "radar_type": "RDY-2",
            "radar_range_km": 150,
            "rcs_m2": 2.0,
            "irst": False,
            "ecm_suite": "ICMS Mk3",
            "ecm_rating": 60,
            "chaff_count": 96,
            "flare_count": 32,
            "towed_decoy": False,
            "unlock_cost": 65000,
            "maintenance_cost": 4000,
        },
        {
            "name": "Eurofighter Typhoon",
            "origin": "Europe",
            "role": "air_superiority",
            "generation": "4.5",
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/7/7e/Luftwaffe_Eurofighter_Typhoon.JPG",
            "max_speed_mach": 2.0,
            "max_speed_loaded_mach": 1.5,
            "combat_radius_km": 1390,
            "service_ceiling_ft": 65000,
            "max_g_load": 9.0,
            "thrust_to_weight_clean": 1.18,
            "wing_loading_kg_m2": 312,
            "instantaneous_turn_rate_deg_s": 29,
            "sustained_turn_rate_deg_s": 23,
            "empty_weight_kg": 11000,
            "max_takeoff_weight_kg": 23500,
            "internal_fuel_kg": 5000,
            "max_payload_kg": 9000,
            "hardpoints": 13,
            "compatible_weapons": json.dumps([
                weapon_id_map.get("Meteor"),
                weapon_id_map.get("AIM-120C AMRAAM"),
                weapon_id_map.get("AIM-9X Sidewinder"),
            ]),
            "radar_type": "Captor-E AESA",
            "radar_range_km": 200,
            "rcs_m2": 0.5,
            "irst": True,
            "ecm_suite": "Praetorian DASS",
            "ecm_rating": 88,
            "chaff_count": 120,
            "flare_count": 48,
            "towed_decoy": True,
            "unlock_cost": 130000,
            "maintenance_cost": 9000,
        },
    ]

    for a_data in aircraft_list:
        existing = db.query(Aircraft).filter(Aircraft.name == a_data["name"]).first()
        if not existing:
            db.add(Aircraft(**a_data))

    # ── SHIPS ──

    ships = [
        {
            "name": "INS Chennai",
            "class_name": "Kolkata",
            "origin": "India",
            "ship_type": ShipType.DESTROYER,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/9/95/INS_Chennai_%28D65%29_at_sea.jpg",
            "displacement_tons": 7500,
            "max_speed_knots": 30,
            "crew": 300,
            "radar_type": "MF-STAR AESA",
            "radar_range_km": 250,
            "sonar": "HUMSA-NG",
            "helicopter": "Sea King Mk42B",
            "anti_ship_missiles": json.dumps([{"weapon_id": weapon_id_map.get("BrahMos"), "count": 16}]),
            "sam_systems": json.dumps([{"weapon_id": weapon_id_map.get("Barak-8"), "count": 32}]),
            "ciws": json.dumps([{"weapon_id": weapon_id_map.get("AK-630"), "count": 2}]),
            "torpedoes": json.dumps([]),
            "gun": "OTO Melara 76mm Super Rapid",
            "ecm_suite": "Ajanta Mk2",
            "ecm_rating": 75,
            "decoys": "Kavach",
            "compartments": 15,
            "unlock_cost": 500000,
            "maintenance_cost": 25000,
        },
        {
            "name": "INS Visakhapatnam",
            "class_name": "Visakhapatnam",
            "origin": "India",
            "ship_type": ShipType.DESTROYER,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/54/INS_Visakhapatnam_%28D66%29_during_commissioning_ceremony.jpg",
            "displacement_tons": 7400,
            "max_speed_knots": 30,
            "crew": 310,
            "radar_type": "MF-STAR AESA (upgraded)",
            "radar_range_km": 270,
            "sonar": "HUMSA-NG",
            "helicopter": "MH-60R",
            "anti_ship_missiles": json.dumps([{"weapon_id": weapon_id_map.get("BrahMos"), "count": 8}]),
            "sam_systems": json.dumps([{"weapon_id": weapon_id_map.get("Barak-8"), "count": 32}]),
            "ciws": json.dumps([{"weapon_id": weapon_id_map.get("AK-630"), "count": 4}]),
            "torpedoes": json.dumps([]),
            "gun": "OTO Melara 76mm Super Rapid",
            "ecm_suite": "Ajanta Mk2E",
            "ecm_rating": 78,
            "decoys": "Kavach Mk2",
            "compartments": 16,
            "unlock_cost": 520000,
            "maintenance_cost": 26000,
        },
        {
            "name": "Type 052D Kunming",
            "class_name": "Luyang III",
            "origin": "China",
            "ship_type": ShipType.DESTROYER,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/d8/A_Type_052D_destroyer_sail_with_PLANS_Shandong_%28CV-17%29_20240719.jpg",
            "displacement_tons": 7500,
            "max_speed_knots": 29,
            "crew": 280,
            "radar_type": "Type 346A AESA",
            "radar_range_km": 300,
            "sonar": "MGK-335",
            "helicopter": "Ka-28",
            "anti_ship_missiles": json.dumps([{"weapon_id": weapon_id_map.get("YJ-18"), "count": 8}]),
            "sam_systems": json.dumps([{"weapon_id": weapon_id_map.get("HHQ-9"), "count": 64}]),
            "ciws": json.dumps([{"weapon_id": weapon_id_map.get("Phalanx CIWS"), "count": 1}]),
            "torpedoes": json.dumps([]),
            "gun": "H/PJ-45 130mm",
            "ecm_suite": "Type 726-4",
            "ecm_rating": 68,
            "decoys": "Type 726 decoy launcher",
            "compartments": 14,
            "unlock_cost": 480000,
            "maintenance_cost": 24000,
        },
        {
            "name": "USS Arleigh Burke IIA",
            "class_name": "Arleigh Burke",
            "origin": "USA",
            "ship_type": ShipType.DESTROYER,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/ba/USN_Arleigh_Burke_Class_Destroyer.JPEG",
            "displacement_tons": 9200,
            "max_speed_knots": 31,
            "crew": 323,
            "radar_type": "AN/SPY-1D(V) PESA",
            "radar_range_km": 320,
            "sonar": "AN/SQQ-89",
            "helicopter": "MH-60R Seahawk",
            "anti_ship_missiles": json.dumps([{"weapon_id": weapon_id_map.get("Harpoon"), "count": 8}]),
            "sam_systems": json.dumps([{"weapon_id": weapon_id_map.get("SM-2 Standard"), "count": 96}]),
            "ciws": json.dumps([{"weapon_id": weapon_id_map.get("Phalanx CIWS"), "count": 2}]),
            "torpedoes": json.dumps([]),
            "gun": "Mk 45 5-inch/127mm",
            "ecm_suite": "AN/SLQ-32(V)3",
            "ecm_rating": 82,
            "decoys": "Mk 36 SRBOC",
            "compartments": 18,
            "unlock_cost": 600000,
            "maintenance_cost": 30000,
        },
        {
            "name": "Admiral Gorshkov",
            "class_name": "Gorshkov",
            "origin": "Russia",
            "ship_type": ShipType.FRIGATE,
            "image_url": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Admiral_Gorshkov_frigate_01.jpg",
            "displacement_tons": 5400,
            "max_speed_knots": 30,
            "crew": 210,
            "radar_type": "Poliment-Redut AESA",
            "radar_range_km": 200,
            "sonar": "Zarya-2",
            "helicopter": "Ka-27",
            "anti_ship_missiles": json.dumps([{"weapon_id": weapon_id_map.get("BrahMos"), "count": 16}]),
            "sam_systems": json.dumps([{"weapon_id": weapon_id_map.get("Barak-8"), "count": 32}]),
            "ciws": json.dumps([{"weapon_id": weapon_id_map.get("AK-630"), "count": 2}]),
            "torpedoes": json.dumps([]),
            "gun": "A-192M 130mm",
            "ecm_suite": "5P-10 Puma",
            "ecm_rating": 70,
            "decoys": "PK-10 Smerch",
            "compartments": 12,
            "unlock_cost": 350000,
            "maintenance_cost": 18000,
        },
    ]

    for s_data in ships:
        existing = db.query(Ship).filter(Ship.name == s_data["name"]).first()
        if not existing:
            db.add(Ship(**s_data))

    db.commit()

    # ── BATTLE-TYPE MISSION TEMPLATES ──

    from app.models.contract import MissionTemplate, Faction

    # Look up aircraft/ship IDs by name
    def get_ac_id(name):
        ac = db.query(Aircraft).filter(Aircraft.name == name).first()
        return ac.id if ac else None

    def get_ship_id(name):
        s = db.query(Ship).filter(Ship.name == name).first()
        return s.id if s else None

    # Delete old battle missions and re-seed with objective-based missions
    old_missions = db.query(MissionTemplate).all()
    for m in old_missions:
        db.delete(m)
    db.flush()

    battle_missions = [
        # ─── Sahara Crisis chapter (air, min_rank=0) ───
        {
            "title": "Desert Patrol",
            "description": "Patrol the Western Desert Corridor and engage any hostile aircraft. Standard air superiority rules of engagement.",
            "faction": Faction.SAHARA_SINDICATE,
            "required_unit_types": '["fighter"]',
            "base_payout": 25000,
            "risk_level": 40,
            "political_impact": 5,
            "estimated_duration_hours": 4,
            "battle_type": "air",
            "mission_objective": "air_superiority",
            "difficulty": 1,
        },
        {
            "title": "Convoy Escort",
            "description": "Escort a humanitarian convoy through hostile airspace. Protect the convoy from enemy fighters for the duration of the transit.",
            "faction": Faction.SAHARA_SINDICATE,
            "required_unit_types": '["fighter"]',
            "base_payout": 40000,
            "risk_level": 60,
            "political_impact": 10,
            "estimated_duration_hours": 6,
            "battle_type": "air",
            "mission_objective": "escort",
            "difficulty": 2,
        },
        {
            "title": "Air Dominance",
            "description": "Establish air dominance over the desert corridor. Engage and neutralize all enemy air assets in the sector.",
            "faction": Faction.SAHARA_SINDICATE,
            "required_unit_types": '["fighter"]',
            "base_payout": 45000,
            "risk_level": 65,
            "political_impact": 15,
            "estimated_duration_hours": 4,
            "battle_type": "air",
            "mission_objective": "air_superiority",
            "difficulty": 2,
        },
        # ─── Pacific Tensions chapter (naval + mixed, min_rank=1) ───
        {
            "title": "Strait Patrol",
            "description": "Patrol disputed strait waters and deter hostile naval activity. Rules of engagement: weapons free on confirmed threats.",
            "faction": Faction.PACIFIC_ALLIANCE,
            "required_unit_types": '["destroyer"]',
            "base_payout": 35000,
            "risk_level": 50,
            "political_impact": 10,
            "estimated_duration_hours": 8,
            "battle_type": "naval",
            "mission_objective": "naval_patrol",
            "difficulty": 1,
            "enemy_ship_id": get_ship_id("Type 052D Kunming"),
        },
        {
            "title": "Air Cover",
            "description": "Provide air cover for allied naval forces transiting through contested waters. Protect the fleet from enemy air strikes.",
            "faction": Faction.PACIFIC_ALLIANCE,
            "required_unit_types": '["fighter"]',
            "base_payout": 45000,
            "risk_level": 60,
            "political_impact": 10,
            "estimated_duration_hours": 6,
            "battle_type": "air",
            "mission_objective": "escort",
            "difficulty": 2,
        },
        {
            "title": "Surface Action",
            "description": "Engage enemy surface combatants threatening allied shipping lanes. Expect a determined adversary with anti-ship missiles.",
            "faction": Faction.PACIFIC_ALLIANCE,
            "required_unit_types": '["destroyer"]',
            "base_payout": 55000,
            "risk_level": 70,
            "political_impact": 15,
            "estimated_duration_hours": 8,
            "battle_type": "naval",
            "mission_objective": "naval_patrol",
            "difficulty": 2,
            "enemy_ship_id": get_ship_id("USS Arleigh Burke IIA"),
        },
        # ─── Arctic Shadow chapter (stealth/recon, min_rank=2) ───
        {
            "title": "Northern Intercept",
            "description": "Intercept an unidentified aircraft approaching the Arctic exclusion zone. Do not let it escape.",
            "faction": Faction.ATLANTIC_COALITION,
            "required_unit_types": '["fighter"]',
            "base_payout": 50000,
            "risk_level": 65,
            "political_impact": -5,
            "estimated_duration_hours": 4,
            "battle_type": "air",
            "mission_objective": "interception",
            "difficulty": 2,
        },
        {
            "title": "Shadow Recon",
            "description": "Conduct a reconnaissance sortie to gather intelligence on enemy air capabilities. Gather intel and RTB safely.",
            "faction": Faction.ATLANTIC_COALITION,
            "required_unit_types": '["fighter"]',
            "base_payout": 55000,
            "risk_level": 55,
            "political_impact": -10,
            "estimated_duration_hours": 5,
            "battle_type": "air",
            "mission_objective": "recon",
            "difficulty": 2,
        },
        {
            "title": "Arctic Dominance",
            "description": "Strike deep into enemy-held Arctic airspace. Push through enemy air defenses and reach the target zone.",
            "faction": Faction.ATLANTIC_COALITION,
            "required_unit_types": '["fighter"]',
            "base_payout": 70000,
            "risk_level": 80,
            "political_impact": -15,
            "estimated_duration_hours": 6,
            "battle_type": "air",
            "mission_objective": "strike",
            "difficulty": 3,
        },
        # ─── Standalone (always available, no chapter) ───
        {
            "title": "Training Sortie",
            "description": "A routine training sortie against a simulated adversary. Low risk, good for new pilots.",
            "faction": Faction.DESERT_BLOC,
            "required_unit_types": '["fighter"]',
            "base_payout": 15000,
            "risk_level": 25,
            "political_impact": 0,
            "estimated_duration_hours": 3,
            "battle_type": "air",
            "mission_objective": "air_superiority",
            "difficulty": 1,
        },
        {
            "title": "Fleet Defense Drill",
            "description": "Participate in a fleet defense exercise. Engage simulated enemy surface contacts in a controlled environment.",
            "faction": Faction.DESERT_BLOC,
            "required_unit_types": '["destroyer"]',
            "base_payout": 20000,
            "risk_level": 30,
            "political_impact": 0,
            "estimated_duration_hours": 6,
            "battle_type": "naval",
            "mission_objective": "naval_patrol",
            "difficulty": 1,
            "enemy_ship_id": get_ship_id("Admiral Gorshkov"),
        },
    ]

    for m_data in battle_missions:
        db.add(MissionTemplate(**m_data))

    db.commit()

    # ── STARTING OWNED AIRCRAFT & SHIP FOR DEFAULT USER ──

    from app.models.owned_aircraft import OwnedAircraft
    from app.models.owned_ship import OwnedShip
    from app.models.user import User

    user = db.query(User).filter(User.username == "commander").first()
    if user:
        # Give starting aircraft if none owned
        existing_ac = db.query(OwnedAircraft).filter(OwnedAircraft.user_id == user.id).count()
        if existing_ac == 0:
            rafale_id = get_ac_id("Dassault Rafale")
            if rafale_id:
                db.add(OwnedAircraft(user_id=user.id, aircraft_id=rafale_id, condition=100))

        # Give starting ship if none owned
        existing_ship = db.query(OwnedShip).filter(OwnedShip.user_id == user.id).count()
        if existing_ship == 0:
            chennai_id = get_ship_id("INS Chennai")
            if chennai_id:
                db.add(OwnedShip(user_id=user.id, ship_id=chennai_id, condition=100))

        # Give starting weapons if none owned
        from app.models.owned_weapon import OwnedWeapon
        existing_weapons = db.query(OwnedWeapon).filter(OwnedWeapon.user_id == user.id).count()
        if existing_weapons == 0:
            starting_weapons = {
                "MICA EM": 8,
                "MICA IR": 4,
                "Meteor": 4,
            }
            for wname, qty in starting_weapons.items():
                wid = weapon_id_map.get(wname)
                if wid:
                    db.add(OwnedWeapon(user_id=user.id, weapon_id=wid, quantity=qty))

        db.commit()
